name: Update version.json on release

on:
  release:
    types: [published]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "{ \"version\": \"${VERSION}\", \"url\": \"https://github.com/${{ github.repository }}/releases/latest/download/Update.zip\" }" > version.json
          git add version.json
          git commit -m "Update version.json to $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
